accounts/urls.py
"""trading_bot URL Configuration
"""

from django.urls import path
from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    ForgotPasswordView,
    ResetPasswordView,
    LandingView,
    ContactUsView,
    Recover,
    RecoverDone,
    Reset,
    ResetDone,
)

# from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this

app_name = 'accounts'

urlpatterns = [
    path('', LandingView.as_view(), name="landing-page"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('forgot-password/', ForgotPasswordView.as_view(), name="forgot-password"),
    # path('reset-password/', ResetPasswordView.as_view(), name="reset-password"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path(r'recover/(<signature>)/', RecoverDone.as_view(), name='password_reset_sent'),
    path('recover/', Recover.as_view(), name='password_reset_recover'),
    path('reset/done/', ResetDone.as_view(), name='password_reset_done'),
    path(r'reset/(<token>)/', Reset.as_view(), name='password_reset_reset'),
    path('contact-us/', ContactUsView.as_view(), name="contat-us"),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from core import views
from django.contrib import admin
from django.conf import settings
from django.urls import path,reverse_lazy
from django.conf.urls.static import static

urlpatterns = [
    # FOR MAIN DASHBOARD VIEW
    path('myprofile/', views.MyProfileView.as_view(),name='myprofile'),
    path('contactus/', views.ContactUsView.as_view(),name='contactus'),
    
    path('facial-ubtan/', views.FacialUbtanView.as_view(), name='facial_ubtan'),
    path('kumkumadi-oil/', views.KumkumadiOilView.as_view(), name='kumkumadi_oil'),
    path('peel-off-mask/', views.PeelOfMaskView.as_view(), name='peel_off_mask'),
    path('bentonite-clay-mask/', views.BenetoniteClayMaskView.as_view(), name='bentonite_clay_mask'),
    path('moroccan-clay-mask/', views.MorrocanClayMaskView.as_view(), name='moroccan_clay_mask'),
    
    path('hair-oil/', views.HairOilView.as_view(), name='hair_oil'),
    
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy_policy'),
    
    path('about/', views.AboutUsView.as_view(), name='about'),
]

cosmetic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('core/',include(('core.urls','core'),namespace='core')),
    path('admin/',admin.site.urls),
    path('', include(('accounts.urls','accounts'),namespace='accounts')),
    
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


accounts/models.py
from email.policy import default
from enum import unique
from statistics import mode
from unittest.util import _MAX_LENGTH
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin,AbstractUser,BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from django.conf import settings
from django.apps import apps


USER_TYPES=[
    ('ADMIN', 'admin'),
    ('USER', 'user'),
    
]
class CustomUser(AbstractUser):
    firstname = models.CharField(max_length=50,null=True,blank=True)
    lastname = models.CharField(max_length=50,null=True,blank=True)
    username = models.CharField(max_length=50,null=True,blank=True)
    type = models.CharField(max_length=10,choices=USER_TYPES,null=True,blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField("Date and time", auto_now_add=True,null=True)
    status = models.BooleanField(default=False, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def __str__(self):
        return_str = None
        if self.username:
            return_str = self.username
        else:
            return_str = self.email
        return return_str

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    def get_initials(self):
        if not self.username:
            return ""
        parts = self.username.split()
        initials = "".join([part[0].upper() for part in parts])
        return initials

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect
from .forms import (
    LoginForm,
    SignUpForm,
    ForgotPasswordForm,
    ResetPasswordForm
)
from django.views.generic import View
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import Group
from django.forms import ValidationError
from django.contrib.auth import get_user_model

from django.contrib.sites.shortcuts import get_current_site
from django.core import signing
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.debug import sensitive_post_parameters
import datetime
from .forms import PasswordRecoveryForm, PasswordResetForm
from .signals import user_recovers_password
from .models import CustomUser
import uuid
from core.models import *
import random
from core.email_send_config import send_admin_mail, send_user_mail
User = get_user_model()

class LandingView(View):
    
    def get(self, request):
        context = {}
        if request.user.is_authenticated:
            if request.user.is_superuser:
                return redirect("core:admin-profile")
            else:
                # return redirect("core:myprofile")
                print("user.....")
        return render(request, 'accounts/landing-page.html', context)
    
    def post(self, request):
        return render(request, 'accounts/landing-page.html')
        
class ContactUsView(View):
    
    def get(self, request):
        return render(request, 'accounts/contact-us.html')
        
    def post(self, request):
        return render(request, 'accounts/contact-us.html')

class LoginView(View):
    def get(self,request):
        if request.user.is_authenticated:
            return redirect("core/myprofile/")
        else:
            form = LoginForm(request.POST or None)
            return render(request, "accounts/login.html", {"form": form })

    def post(self,request):
        form = LoginForm(request.POST or None)

        msg = None

        if request.method == "POST":

            if form.is_valid():
                email = form.cleaned_data.get("email")
                password = form.cleaned_data.get("password")
                user = authenticate(username=email, password=password)
                if user is not None:
                    login(request, user)
                    if user.is_superuser:
                        print("ifff.....")
                        return redirect("core:admin-profile")
                    else:
                        print("elseeee.....")
                        return redirect("accounts:landing-page")
                else:
                    # messages.add_message(request, messages.WARNING, 'User name and password does not match')
                    msg = ('User name/Email and password does not match',)
                    form.fields['email'].widget.attrs['class']="form-control is-invalid"
                    form.fields['password'].widget.attrs['class']="form-control is-invalid"
                    form.add_error("email",ValidationError(msg[0]))
                    messages.error(request, 'Email or Password is incorrect, Please try again!')
            else:
                msg = ('Please fill all the required fields',)
                form.add_error("email",ValidationError(msg[0]))
                print("field requires")

        return render(request, "accounts/login.html", {"form": form, "msg" : msg})

class ForgotPasswordView(View):
    def get(self,request):
        form = ForgotPasswordForm(request.POST or None)
        return render(request, "accounts/forgot-password.html", {"form": form })

    def post(self,request):
        form = ForgotPasswordForm(request.POST or None)

        msg = None

        if request.method == "POST":

            if form.is_valid():
                email = form.cleaned_data.get("email")
                is_user = User.objects.filter(email=email).exists()
                if is_user:
                    reset_form = ResetPasswordForm(initial={"email":email})
                    return render(request, "accounts/reset-password.html", {"form": reset_form, "msg" : msg})
                else:
                    # messages.add_message(request, messages.WARNING, 'User name and password does not match')
                    print(email)
                    msg = ('Enter the email address registered on your account',)
                    form.fields['email'].widget.attrs['class']="form-control is-invalid"
                    form.add_error("email",ValidationError(msg[0]))
            else:
                msg = ('Please fill all the required fields',)
                form.add_error("email",ValidationError(msg[0]))
                print("field requires")

        return render(request, "accounts/forgot-password.html", {"form": form, "msg" : msg})

class ResetPasswordView(View):
    def get(self,request):
        form = ResetPasswordForm(request.POST or None)
        return render(request, "accounts/forgot-password.html", {"form": form })

    def post(self,request):
        form = ResetPasswordForm(request.POST or None)

        if request.method == "POST":

            if form.is_valid():
                email = form.cleaned_data.get("email")
                password1 = form.cleaned_data.get("password1")
                
                user = User.objects.get(email=email)
                user.set_password(password1)
                user.save()
                return redirect("accounts:login")

        return render(request, "accounts/reset-password.html", {"form": form })

class RegisterView(View):
    def get(self, request):
        print(request)
        form = SignUpForm(request.GET)
        print("hi")
        return render(request, "accounts/register.html", {"form": form })

    def post(self, request):
        print("form")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.type = request.POST.get('type')  # Get the type from the POST data
            user.save()
            send_admin_mail(f"User Create", f"{ user.username } is created - ({ user.type })")
            messages.success(request, 'User created Successfully, Please Login!')
            return redirect("accounts:login")
        else:
            messages.error(request, form.errors)
        return render(request, "accounts/register.html", {"form": form,})
    
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/")


class SaltMixin(object):
    salt = 'password_recovery'
    url_salt = 'password_recovery_url'


def loads_with_timestamp(value, salt):
    """Returns the unsigned value along with its timestamp, the time when it
    got dumped."""
    try:
        signing.loads(value, salt=salt, max_age=-999999)
    except signing.SignatureExpired as e:
        age = float(str(e).split('Signature age ')[1].split(' >')[0])
        timestamp = timezone.now() - datetime.timedelta(seconds=age)
        return timestamp, signing.loads(value, salt=salt)


class RecoverDone(SaltMixin, generic.TemplateView):
    template_name = 'accounts/reset_sent.html'

    def get_context_data(self, **kwargs):
        ctx = super(RecoverDone, self).get_context_data(**kwargs)
        try:
            ctx['timestamp'], ctx['email'] = loads_with_timestamp(
                self.kwargs['signature'], salt=self.url_salt,
            )
        except signing.BadSignature:
            raise Http404
        return ctx

class Recover(SaltMixin, generic.FormView):
    case_sensitive = True
    form_class = PasswordRecoveryForm
    template_name = 'accounts/recovery_form.html'
    success_url_name = 'accounts:password_reset_sent'
    email_template_name = 'accounts/recovery_email.txt'
    email_subject_template_name = 'accounts/recovery_email_subject.txt'
    search_fields = ['username', 'email']

    def get_success_url(self):
        return reverse(self.success_url_name, args=[self.mail_signature])

    def get_context_data(self, **kwargs):
        kwargs['url'] = self.request.get_full_path()
        return super(Recover, self).get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super(Recover, self).get_form_kwargs()
        kwargs.update({
            'case_sensitive': self.case_sensitive,
            'search_fields': self.search_fields,
        })
        return kwargs

    def get_site(self):
        return get_current_site(self.request)

    def send_notification(self):
        context = {
            'site': self.get_site(),
            'user': self.user,
            'username': self.user.get_username(),
            'token': signing.dumps(self.user.pk, salt=self.salt),
            'secure': self.request.is_secure(),
        }
        body = loader.render_to_string(self.email_template_name,
                                       context).strip()
        subject = loader.render_to_string(self.email_subject_template_name,
                                          context).strip()
        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL,
                  [self.user.email])

    def form_valid(self, form):
        self.user = form.cleaned_data['user']
        self.send_notification()
        if (
            len(self.search_fields) == 1 and
            self.search_fields[0] == 'username'
        ):

templates/accounts/forgot-password.html

{% extends "./base.html" %}
{% block title %}
    Forgot Password
{% endblock title %}

{% block content %}
    <!-- BACKGROUND-IMAGE -->
    <div class="login-img">

        <!-- GLOABAL LOADER -->
        <div id="global-loader">
            <img src="/static/assets/images/loader.svg" class="loader-img" alt="Loader">
        </div>
        <!-- End GLOABAL LOADER -->

        <!-- PAGE -->
        <div class="page">
            <div class="">

                <!-- CONTAINER OPEN -->
                <div class="col col-login mx-auto">
                    <div class="text-center">
                        <img src="/static/assets/images/brand/logo-white.png" class="header-brand-img m-0" alt="">
                    </div>
                </div>

                <!-- CONTAINER OPEN -->
                <div class="container-login100">
                    <div class="wrap-login100 p-6">
                        <form class="login100-form validate-form" action="{% url 'accounts:forgot-password' %}" method="post">
                        {% csrf_token %}
                            <span class="login100-form-title pb-5">
                                Forgot Password
                            </span>
                            <p class="text-muted">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %} 
                                    <div class="alert alert-danger" role="alert">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                            </p>
                            <div class="wrap-input100 validate-input input-group" data-bs-validate="Valid email is required: ex@abc.xyz">
                                <a href="javascript:void(0)" class="input-group-text bg-white text-muted">
                                    <i class="zmdi zmdi-email" aria-hidden="true"></i>
                                </a>
                                {{ form.email }}
                            </div>
                            <div class="submit">
                                <input type="submit" class="login100-form-btn btn-primary" value="Submit" />
                            </div>
                            <div class="text-center mt-4">
                                <p class="text-dark mb-0">Forgot It?<a class="text-primary ms-1" href="/accounts/login/">Send me Back</a></p>
                            </div>
                                                 
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--END PAGE -->

    </div>
    <!-- BACKGROUND-IMAGE CLOSED -->

</body>
{% endblock content%}

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="/static/assets/images/logo/Akshada Logo3.png" type="image/x-icon">
    <link rel="shortcut icon" href="/static/assets/images/logo/Akshada Logo3.png" type="image/x-icon">
    <title>Login</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/fontawesome.css">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/icofont.css">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/themify.css">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/flag-icon.css">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/feather-icon.css">
    <!-- Plugins css start-->
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
    <link id="color" rel="stylesheet" href="/static/assets/css/color-1.css" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/responsive.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet"> 
  </head>
  <body>
    <!-- login page start-->
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-7 order-1"><img class="bg-img-cover bg-center" src="/static/assets/images/login/6.jpg" alt="looginpage"></div>
        <div class="col-xl-5 p-0">
          <div class="login-card login-dark">
            <div>
              <div>
                <a class="logo text-start d-flex align-items-center mb-2" href="index.html">
                  <img class="img-fluid for-light" style="height: 80px !important;" src="/static/assets/images/logo/Akshada Logo3.png" alt="loginpage">
                  <div class="ms-3">
                    <h2 class="mb-0" style="color: #C9A264; font-family: 'Playfair Display', serif;">AKSHADA</h2>
                    <h5 style="color: #C9A264; font-family: 'Playfair Display', serif;">ayurveda</h5>
                  </div>
                </a>  
              </div>
              <div class="login-main"> 
                <form class="theme-form" method="post">
                  {% csrf_token %}
                  <h4>Sign in to account</h4>
                  <p>Enter your email & password to login</p>
                  <div class="form-group">
                    <label class="col-form-label">Email Address</label>
                    {{ form.email }}
                  </div>
                  <div class="form-group">
                    <label class="col-form-label">Password</label>
                    <div class="form-input position-relative">
                      {{ form.password }}
                    </div>
                  </div>
                  <div class="form-group mb-0">
                    {% comment %} <div class="checkbox p-0">
                      <input id="checkbox1" type="checkbox">
                      <label class="text-muted" for="checkbox1">Remember password</label>
                    </div>
                    <a class="link" href="forget-password.html">Forgot password?</a> {% endcomment %}
                    <div class="text-end mt-3">
                      <button class="btn btn-primary btn-block w-100" type="submit">Sign in</button>
                    </div>
                  </div>
                  <p class="mt-4 mb-0 text-center">Don't have account?<a class="ms-2" href="{% url "accounts:register" %}">Create Account</a></p>
                  <script>
                    (function() {
                    'use strict';
                    window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                    }, false);
                    });
                    }, false);
                    })();
                    
                  </script>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- latest jquery-->
      <script src="/static/assets/js/jquery.min.js"></script>
      <!-- Bootstrap js-->
      <script src="/static/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
      <!-- feather icon js-->
      <script src="/static/assets/js/icons/feather-icon/feather.min.js"></script>
      <script src="/static/assets/js/icons/feather-icon/feather-icon.js"></script>
      <!-- scrollbar js-->
      <!-- Sidebar jquery-->
      <script src="/static/assets/js/config.js"></script>
      <!-- Plugins JS start-->
      <!-- Plugins JS Ends-->
      <!-- Theme js-->
      <script src="/static/assets/js/script.js"></script>
      <script src="/static/assets/js/script1.js"></script>
    </div>
  </body>
</html>

templates/accounts/recovery_done.html
{% extends "base.html" %}{% load i18n %}

{% block title %}{% trans "New password set" %}{% endblock %}

{% block navbar %}
{% endblock navbar %}

{% block navbar-2 %}
{% endblock navbar-2 %}

{% block app-header %}
{% endblock app-header %}

{% block content %}
	<p>{% block trans %}
	 Your password has successfully been reset. return to <a href="{% url 'accounts:login' %}"> Login Page. </a>
	 {% endblock trans %}
	 </p>


	  <script>
         setTimeout(function(){
            window.location.href = "{% url 'accounts:login' %}";
         }, 10000);
      </script>
{% endblock content %}

{% block whatsapp %}
{% endblock whatsapp %}

{% block footer %}
{% endblock footer %}

templates/accounts/recovery_form.html
{% extends "base.html"%}

{% block title %}
New password set
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block navbar-2 %}
{% endblock navbar-2 %}

{% block app-header %}
{% endblock app-header %}

{% block content %}
<body class="app sidebar-mini ltr login-img">

    <!-- BACKGROUND-IMAGE -->
    <div class="">

        <!-- GLOABAL LOADER -->
        <div id="global-loader">
            <img src="assets/images/loader.svg" class="loader-img" alt="Loader">
        </div>
        <!-- End GLOABAL LOADER -->

        <!-- PAGE -->
        <div class="page">
            <div class="">
                <!-- Theme-Layout -->

                <!-- CONTAINER OPEN -->
                <div class="col col-login mx-auto">
                    <div class="text-center">
                        <a href="index.html"><img src="assets/images/brand/logo-white.png" class="header-brand-img m-0" alt=""></a>
                    </div>
                </div>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    {% block error_messages %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    <p>{{ message }}</p>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endblock error_messages %}
                {% endif %}
                <!-- CONTAINER OPEN -->
                <div class="container-login100">
                    <div class="wrap-login100 p-6">
                        <form class="login100-form validate-form" role="form" action="{% url 'accounts:password_reset_recover' %}" method="post">
                            {% csrf_token %}
                            <span class="login100-form-title pb-5">
                                Recover Password
                            </span>
                            <p class="text-muted">Enter the email address registered on your account</p>
                            {% comment %} <label>Email</label> {% endcomment %}
                                <div class="mb-3">
                                    {{ form.username_or_email }}
                                </div>
                            <div class="text-center">
                                <input type="submit" class="btn btn-info w-100 mt-4 mb-0" value="Send Link" />
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--END PAGE -->

    </div>
    <!-- BACKGROUND-IMAGE CLOSED -->


</body>
{% endblock content %}

{% block whatsapp %}
{% endblock whatsapp %}

{% block footer %}
{% endblock footer %}

templates/accounts/reset_sent.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Password recovery sent" %}{% endblock %}

{% block navbar %}
{% endblock navbar %}

{% block navbar-2 %}
{% endblock navbar-2 %}

{% block app-header %}
{% endblock app-header %}

{% block content %}
	<p>{% blocktrans with ago=timestamp|timesince %}An email was sent to <strong>{{ email }}</strong> {{ ago }} ago. Use the link in it to set a new password.{% endblocktrans %}</p>

	 <script>
         setTimeout(function(){
            window.location.href = "{% url 'accounts:login' %}";
         }, 10000);
      </script>
{% endblock %}

{% block whatsapp %}
{% endblock whatsapp %}

{% block footer %}
{% endblock footer %}