accounts/urls.py
"""trading_bot URL Configuration
"""

from django.urls import path
from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    ForgotPasswordView,
    ResetPasswordView,
    LandingView,
    ContactUsView,
    Recover,
    RecoverDone,
    Reset,
    ResetDone,
)

# from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this

app_name = 'accounts'

urlpatterns = [
    path('', LandingView.as_view(), name="landing-page"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('forgot-password/', ForgotPasswordView.as_view(), name="forgot-password"),
    # path('reset-password/', ResetPasswordView.as_view(), name="reset-password"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path(r'recover/(<signature>)/', RecoverDone.as_view(), name='password_reset_sent'),
    path('recover/', Recover.as_view(), name='password_reset_recover'),
    path('reset/done/', ResetDone.as_view(), name='password_reset_done'),
    path(r'reset/(<token>)/', Reset.as_view(), name='password_reset_reset'),
    path('contact-us/', ContactUsView.as_view(), name="contat-us"),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from core import views
from django.contrib import admin
from django.conf import settings
from django.urls import path,reverse_lazy
from django.conf.urls.static import static

urlpatterns = [
    # FOR MAIN DASHBOARD VIEW
    path('myprofile/', views.MyProfileView.as_view(),name='myprofile'),
    path('contactus/', views.ContactUsView.as_view(),name='contactus'),
    
    path('facial-ubtan/', views.FacialUbtanView.as_view(), name='facial_ubtan'),
    path('kumkumadi-oil/', views.KumkumadiOilView.as_view(), name='kumkumadi_oil'),
    path('peel-off-mask/', views.PeelOfMaskView.as_view(), name='peel_off_mask'),
    path('bentonite-clay-mask/', views.BenetoniteClayMaskView.as_view(), name='bentonite_clay_mask'),
    path('moroccan-clay-mask/', views.MorrocanClayMaskView.as_view(), name='moroccan_clay_mask'),
    
    path('hair-oil/', views.HairOilView.as_view(), name='hair_oil'),
    
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy_policy'),
    
    path('about/', views.AboutUsView.as_view(), name='about'),
]

cosmetic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('core/',include(('core.urls','core'),namespace='core')),
    path('admin/',admin.site.urls),
    path('', include(('accounts.urls','accounts'),namespace='accounts')),
    
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 401</title>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,600,700');
        @import url('https://fonts.googleapis.com/css?family=Catamaran:400,800');
        .error-container {
        text-align: center;
        font-size: 106px;
        font-family: 'Catamaran', sans-serif;
        font-weight: 800;
        margin: 70px 15px;
        }
        .error-container > span {
        display: inline-block;
        position: relative;
        }
        .error-container > span.four {
        width: 136px;
        height: 43px;
        border-radius: 999px;
        background:
            linear-gradient(140deg, rgba(0, 0, 0, 0.1) 0%, rgba(0, 0, 0, 0.07) 43%, transparent 44%, transparent 100%),
            linear-gradient(105deg, transparent 0%, transparent 40%, rgba(0, 0, 0, 0.06) 41%, rgba(0, 0, 0, 0.07) 76%, transparent 77%, transparent 100%),
            linear-gradient(to right, #d89ca4, #e27b7e);
        }
        .error-container > span.four:before,
        .error-container > span.four:after {
        content: '';
        display: block;
        position: absolute;
        border-radius: 999px;
        }
        .error-container > span.four:before {
        width: 43px;
        height: 156px;
        left: 60px;
        bottom: -43px;
        background:
            linear-gradient(128deg, rgba(0, 0, 0, 0.1) 0%, rgba(0, 0, 0, 0.07) 40%, transparent 41%, transparent 100%),
            linear-gradient(116deg, rgba(0, 0, 0, 0.1) 0%, rgba(0, 0, 0, 0.07) 50%, transparent 51%, transparent 100%),
            linear-gradient(to top, #99749D, #B895AB, #CC9AA6, #D7969E, #E0787F);
        }
        .error-container > span.four:after {
        width: 137px;
        height: 43px;
        transform: rotate(-49.5deg);
        left: -18px;
        bottom: 36px;
        background: linear-gradient(to right, #99749D, #B895AB, #CC9AA6, #D7969E, #E0787F);
        }

        .error-container > span.zero {
        vertical-align: text-top;
        width: 156px;
        height: 156px;
        border-radius: 999px;
        background: linear-gradient(-45deg, transparent 0%, rgba(0, 0, 0, 0.06) 50%,  transparent 51%, transparent 100%),
            linear-gradient(to top right, #99749D, #99749D, #B895AB, #CC9AA6, #D7969E, #ED8687, #ED8687);
        overflow: hidden;
        animation: bgshadow 5s infinite;
        }
        .error-container > span.zero:before {
        content: '';
        display: block;
        position: absolute;
        transform: rotate(45deg);
        width: 90px;
        height: 90px;
        background-color: transparent;
        left: 0px;
        bottom: 0px;
        background:
            linear-gradient(95deg, transparent 0%, transparent 8%, rgba(0, 0, 0, 0.07) 9%, transparent 50%, transparent 100%),
            linear-gradient(85deg, transparent 0%, transparent 19%, rgba(0, 0, 0, 0.05) 20%, rgba(0, 0, 0, 0.07) 91%, transparent 92%, transparent 100%);
        }
        .error-container > span.zero:after {
        content: '';
        display: block;
        position: absolute;
        border-radius: 999px;
        width: 70px;
        height: 70px;
        left: 43px;
        bottom: 43px;
        background: #FDFAF5;
        box-shadow: -2px 2px 2px 0px rgba(0, 0, 0, 0.1);
        }

        .error-container > span.one {
            vertical-align: text-top;
            width: 43px;
            height: 156px;
            background:
                linear-gradient(to bottom, #99749D, #B895AB, #CC9AA6, #D7969E, #E0787F);
            border-radius: 999px;
            position: relative;
            display: inline-block;
        }
    
        .error-container > span.one:before {
            content: '';
            position: absolute;
            height: 43px;
            transform: rotate(45deg);
            background: linear-gradient(45deg, transparent 0%, transparent 71%, #99749D 72%, #99749D 100%);
            top: -22px;
            left: -22px;
            border-radius: 999px;
        }
    
        .error-container > span.one:after {
            content: '';
            position: absolute;
            height: 43px;
            transform: rotate(45deg);
            background: linear-gradient(45deg, #99749D 0%, #99749D 71%, transparent 72%, transparent 100%);
            left: -11px;
            bottom: 11px;
            border-radius: 999px;
        }

        .screen-reader-text {
            position: absolute;
            top: -9999em;
            left: -9999em;
        }
            
        @keyframes bgshadow {
        0% {
            box-shadow: inset -160px 160px 0px 5px rgba(0, 0, 0, 0.4);
        }
        45% {
            box-shadow: inset 0px 0px 0px 0px rgba(0, 0, 0, 0.1);
        }
        55% {
            box-shadow: inset 0px 0px 0px 0px rgba(0, 0, 0, 0.1);
        }
        100% {
            box-shadow: inset 160px -160px 0px 5px rgba(0, 0, 0, 0.4);
        }
        }

        /* demo stuff */
        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body {
        background-color: #FDFAF5;
        margin-bottom: 50px;
        }
        html, button, input, select, textarea {
            font-family: 'Montserrat', Helvetica, sans-serif;
            color: #bbb;
        }
        h1 {
        text-align: center;
        margin: 30px 15px;
        }
        .zoom-area { 
        max-width: 490px;
        margin: 30px auto 30px;
        font-size: 19px;
        text-align: center;
        }
        .link-container {
        text-align: center;
        }
        a.more-link {
        text-transform: uppercase;
        font-size: 13px;
            background-color: #de7e85;
            padding: 10px 15px;
            border-radius: 0;
            color: #fff;
            display: inline-block;
            margin-right: 5px;
            margin-bottom: 5px;
            line-height: 1.5;
            text-decoration: none;
        margin-top: 50px;
        letter-spacing: 1px;
        }
    </style>
</head>
<body>
    <h1>Sorry, Unauthorized error,</h1>
    <!-- <p class="zoom-area">Sorry, an error has occured, Requested page not found!</p> -->
    <section class="error-container">
    <span class="four"><span class="screen-reader-text">4</span></span>
    <span class="zero"><span class="screen-reader-text">0</span></span>
    <span class="one"><span class="screen-reader-text">1</span></span>
    </section>
    <div class="link-container">
    <a href="/" class="more-link">Go back to Home</a>
    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords"
        content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="/static/assets/images/logo/Akshada Logo3.png" type="image/x-icon">
    <link rel="shortcut icon" href="/static/assets/images/logo/Akshada Logo3.png" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/swiper/swiper-bundle.min.css' %}">

    <title>
        {% block title %}
        title
        {% endblock title %}
    </title>

    {% block css %}

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Ephesis&family=Philosopher&display=swap" rel="stylesheet">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/fontawesome.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/icofont.css">
    <link rel="icon" href="https://admin.pixelstrap.com/cuba/assets/svg/landing-icons.svg">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/slick.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/slick-theme.css">
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/animate.css">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick-theme.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/scrollbar.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/animate.css">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/vendors/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="/static/assets/css/responsive.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet">

    
    <style>
    .navbar-logo {
        height: 80px;
      }
      
      @media (max-width: 1199.98px) {
        .navbar-logo {
          height: 30%;
          max-height: 60px;
        }
      }

    .custom-title-font {
        font-family: 'Philosopher', serif;
    }
    .custom-sub-title-font {
        font-family: 'Ephesis', serif;
        font-size: 32px !important;
    }
    .custom-ingredient-text {
        color: #C9A264 !important;
    }
    </style>
    {% endblock css %}

    {% block extra-css %}
    {% endblock extra-css %}
</head>

<body class="landing-page">
    <!-- tap on top starts-->
    <div class="tap-top"><i data-feather="chevrons-up"></i></div>
    <!-- tap on tap ends-->
    <!-- page-wrapper Start-->
    <div class="landing-page">
        <!-- Page Body Start-->
        <div class="landing-home">
            <div class="container-fluid">
                <div class="sticky-header">
                    <header>
                        {% block navbar %}
                        {% include "navbar.html" %}
                        {% endblock navbar %}
                    </header>
                </div>

                {% block top-content %}
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-sm-10">
                        <div class="content text-center">
                            <div>
                                {% comment %} <h6 class="content-title"><img class="arrow-decore"
                                    src="https://admin.pixelstrap.com/cuba/assets/images/landing/decore/arrow.svg" alt="">
                                    <span class="sub-title">Introducing </span>
                                </h6>
                                <h1 class="wow fadeIn">Akshada Ayurveda<span>Nature's Wisdom</span>for Modern Wellness</h1>
                                <p class="mt-3 wow fadeIn">Discover the power of ancient Ayurvedic traditions combined with modern science. 
                                    Our products are crafted with 100% natural ingredients, bringing you the essence of nature's healing.
                                </p>
                                <p class="mt-2 font-italic">"Embracing nature's purity in every drop, every leaf, every grain."</p> {% endcomment %}
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-8 col-md-10 text-center">
                        <img class="screen1 img-fluid" style="max-width: 70% !important;"
                            src="/static/assets/images/landing/screen4.png" alt="">
                    </div>
                </div>
                {% endblock top-content %}

            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </div>

    {% block product %}
    {% endblock product %}

    <!-- modal --> 
    {% if not user.is_authenticated %}
    {% comment %} <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" onclick="closeModal()" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="modal-toggle-wrapper"> 
                        <h4>Up to<strong class="txt-danger">15% OFF</strong>,On First time registrations, Hurry Up and Shop Now !</h4>
                        <div class="modal-img"><img src="/static/assets/images/gif/online-shopping.gif" alt="online-shopping"></div>
                        <p class="text-sm-center">Discover our premium cosmetic products that blend quality, comfort, and eco-friendliness. Don't miss out on exclusive discounts for first-time customers!</p>
                        <a href="{% url "accounts:register" %}" class="btn bg-primary d-flex align-items-center gap-2 text-light ms-auto justify-content-center">Register Here<i data-feather="arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    {% endif %}

    {% block footer %}
    {% include "footer.html" %}
    {% endblock footer %}
    </div>

    {% block script %}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var modal = document.getElementById('exampleModal');
            modal.style.display = 'block';
            modal.classList.add('show');
        });
    
        function closeModal() {
            var modal = document.getElementById('exampleModal');
            modal.style.display = 'none';
            modal.classList.remove('show');
        }
    </script>

    <!-- latest jquery-->
    <script src="/static/assets/js/jquery-3.5.1.min.js"></script>
    <!-- Bootstrap js-->
    <script src="/static/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- feather icon js-->
    <script src="/static/assets/js/icons/feather-icon/feather.min.js"></script>
    <script src="/static/assets/js/icons/feather-icon/feather-icon.js"></script>
    <!-- Plugins JS start-->
    <script src="/static/assets/js/tooltip-init.js"></script>
    <script src="/static/assets/js/animation/wow/wow.min.js"></script>
    <script src="/static/assets/js/landing_sticky.js"></script>
    <script src="/static/assets/js/landing.js"></script>
    <script src="/static/assets/js/jarallax_libs/libs.min.js"></script>
    <script src="/static/assets/js/slick/slick.min.js"></script>
    <script src="/static/assets/js/slick/slick.js"></script>
    <script src="/static/assets/js/landing-slick.js"></script>
    <script src="/static/assets/js/swiper/swiper-bundle.min.js"></script>
    <!-- Plugins JS Ends-->


    {% comment %} <script src="{% static 'assets/js/jquery.min.js'%}"></script> {% endcomment %}
    <!-- Bootstrap js-->
    {% comment %} <script src="{% static 'assets/js/bootstrap/bootstrap.bundle.min.js' %}"></script> {% endcomment %}
    <!-- feather icon js-->
    <script src="{% static 'assets/js/icons/feather-icon/feather.min.js' %}"></script>
    <script src="{% static 'assets/js/icons/feather-icon/feather-icon.js' %}"></script>
    <!-- scrollbar js-->
    <script src="{% static 'assets/js/scrollbar/simplebar.min.js' %}"></script>
    <script src="{% static 'assets/js/scrollbar/custom.js' %}"></script>
    <!-- Sidebar jquery-->
    <script src="{% static 'assets/js/config.js' %}"></script>
    <!-- Plugins JS start-->
    <script src="{% static 'assets/js/sidebar-menu.js' %}"></script>
    <script src="{% static 'assets/js/sidebar-pin.js' %}"></script>
    <script src="{% static 'assets/js/slick/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/slick/slick.js' %}"></script>
    <script src="{% static 'assets/js/touchspin_2/custom_touchspin.js' %}"></script>
    <script src="{% static 'assets/js/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/custom-swiper/custom_swiper1.js' %}"></script>
    <script src="{% static 'assets/js/dashboard/dashboard_8.js' %}"></script>
    <script src="{% static 'assets/js/height-equal.js' %}"></script>
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="{% static 'assets/js/script.js' %}"></script>
    <script src="{% static 'assets/js/script1.js' %}"></script>
    

    {% endblock script %}

    {% block extra-js %}
    {% endblock extra-js %}
</body>

</html>

templates/footer.html
<footer class="footer-bg">
    <div class="container">
      <div class="landing-center ptb50">
        {% comment %} <div class="feature-content">
          <ul> 
            <li> 
              <h4>Trending Template</h4><img src="/static/assets/images/landing/feature-img.png" alt="leaf golden">
            </li>
            <li> 
              <h4>Overall Best rated Template</h4><img src="/static/assets/images/landing/feature-img.png" alt="leaf golden">
            </li>
            <li> 
              <h4>Weekly Best Seller</h4><img src="/static/assets/images/landing/feature-img.png" alt="leaf golden">
            </li>
          </ul>
        </div> {% endcomment %}
        {% comment %} <div class="landing-title">
          <h2>Build a <span class="gradient-13">stunning site </span> today</h2>
          <p>The Cuba Bootstrap Admin Theme Trusted By Many Developers World Wide.If You like Our Template So Please Rate Us.</p>
        </div> {% endcomment %}
        <div class="footer-content">
          <ul class="license-list">
            <li> <img src="https://admin.pixelstrap.com/cuba/assets/images/landing/icon/right.svg" alt="Right icon">
              <h6>Natural and Organic Ingredients</h6>
            </li>
            <li> <img src="https://admin.pixelstrap.com/cuba/assets/images/landing/icon/right.svg" alt="Right icon">
              <h6>Eco-Friendly Packaging</h6>
            </li>
            <li> <img src="https://admin.pixelstrap.com/cuba/assets/images/landing/icon/right.svg" alt="Right icon">
              <h6>Cruelty-Free Products</h6>
            </li>
          </ul>
        </div>
      </div>
      <div class="sub-footer row g-2">
        <div class="col-md-6"> 
          <h6 class="mb-0">Copyright © 2024 Akshada Ayurveda, All rights reserved.</h6>
        </div>
        <div class="col-md-6"> 
          <ul> 
            <li> 
              <h6 class="mb-0">Find us on</h6>
            </li>
            <li><a href="https://www.instagram.com/akshadaayurveda?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="> <i class="fa-brands fa-instagram"></i></a></li>
            <li> <a href="https://www.facebook.com/AkshadaAyurveda/"><i class="fa-brands fa-facebook"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

templates/navbar.html
<nav class="navbar navbar-b navbar-dark navbar-trans navbar-expand-xl fixed-top nav-padding" id="sidebar-menu">
  <a class="navbar-brand p-0 d-flex align-items-center" href="#">
    <img class="img-fluid navbar-logo" src="/static/assets/images/logo/Akshada Logo4.png" alt="" style="height: 80px;">
    <div class="ms-1 d-none d-sm-block text-start">
      <h2 class="mb-0" style="color: #C9A264; font-family: 'Playfair Display', serif;">AKSHADA</h2>
      <small style="color: #C9A264; font-family: 'Playfair Display', serif;">ayurveda</small>
    </div>
  </a>
    <button class="navbar-toggler navabr_btn-set custom_nav" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
    <div class="navbar-collapse justify-content-center collapse hidenav" id="navbarDefault">
      <ul class="navbar-nav navbar_nav_modify" id="scroll-spy">
        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="skinCareDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Skin Care
          </a>
          <ul class="dropdown-menu" aria-labelledby="skinCareDropdown">
            <li><a class="dropdown-item" href="{% url "core:facial_ubtan" %}">Facial Ubtan</a></li>
            <li><a class="dropdown-item" href="{% url "core:kumkumadi_oil" %}">Kumkumadi Oil</a></li>
            <li><a class="dropdown-item" href="{% url "core:peel_off_mask" %}">Brightening Peel of Mask</a></li>
            <li><a class="dropdown-item" href="{% url "core:bentonite_clay_mask" %}">Benetonite Clay Mask</a></li>
            <li><a class="dropdown-item" href="{% url "core:moroccan_clay_mask" %}">Moroccan Clay Mask</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="hairCareDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hair Care
          </a>
          <ul class="dropdown-menu" aria-labelledby="hairCareDropdown">
            <li><a class="dropdown-item" href="{% url "core:hair_oil" %}">Hair Oil</a></li>
          </ul>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url "core:about" %}">About</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url "core:privacy_policy" %}">privacy policy</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url "core:contactus" %}">Contact Us</a></li>
      </ul>
    </div>
    <div class="mx-2">
      <a href="https://www.instagram.com/akshadaayurveda?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank" class="btn-pill btn-outline-primary border border-primary" style="width: 45px; height: 45px; display: flex; justify-content: center; align-items: center; font-size: 1.4rem;"><i class="fa-brands fa-instagram"></i></a>
    </div>
    <div class="">
      <a href="https://www.facebook.com/AkshadaAyurveda/" target="_blank" class="btn-pill btn-outline-primary border border-primary" style="width: 45px; height: 45px; display: flex; justify-content: center; align-items: center; font-size: 1.4rem;"><i class="fa-brands fa-facebook"></i></a>
    </div>
    {% if user.is_authenticated %}
    <div class="dropdown mx-2">
      <a class="nav-link js-scroll" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: 1.4rem; color: #C45F1E;">
        <i class="fa-solid fa-user" style="vertical-align: middle;"></i>
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
        <li><a class="dropdown-item">{{ request.user.username }}</a></li>
        <li><a class="dropdown-item" href="#">My Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url "accounts:logout" %}">Log Out</a></li>
      </ul>
    </div>
    {% else %}
    <div class="mx-2">
      {% comment %} <a class="nav-link js-scroll" href="{% url "accounts:login" %}" style="font-size: 1.2rem; color: #C45F1E;">
        <i class="fa-solid fa-right-to-bracket" style="vertical-align: middle; margin-right: 5px;"></i>
        <span style="font-size: 1.1rem;"></span>
      </a> {% endcomment %}
      <a href="{% url "accounts:login" %}" class="btn-pill btn-outline-primary border border-primary" style="width: 45px; height: 45px; display: flex; justify-content: center; align-items: center; font-size: 1.4rem;"><i class="fa-solid fa-right-to-bracket"></i></a>
    </div>
    {% endif %}
  </nav>